import * as fs from "fs";
import * as path from "path";

const GLOBALS_DTS = `// Auto-generated by Firestore Explorer — provides IntelliSense for query globals.
// Available globals in every query script: db, auth, app, admin

// ─── Firestore ────────────────────────────────────────────────────────────────

type WhereFilterOp =
  | "==" | "!=" | "<" | "<=" | ">" | ">="
  | "array-contains" | "array-contains-any"
  | "in" | "not-in";

type OrderByDirection = "asc" | "desc";

interface FirestoreTimestamp {
  seconds: number;
  nanoseconds: number;
  toDate(): Date;
  toMillis(): number;
}

interface FirestoreFieldValue {
  // Use FieldValue.serverTimestamp(), increment(), arrayUnion(), arrayRemove(), delete()
}

interface FirestoreGeoPoint {
  latitude: number;
  longitude: number;
}

interface FirestoreDocumentData {
  [key: string]: unknown;
}

interface FirestoreDocumentSnapshot {
  id: string;
  ref: FirestoreDocumentReference;
  exists: boolean;
  createTime?: FirestoreTimestamp;
  updateTime?: FirestoreTimestamp;
  data(): FirestoreDocumentData | undefined;
  get(fieldPath: string): unknown;
}

interface FirestoreQueryDocumentSnapshot extends FirestoreDocumentSnapshot {
  exists: true;
  data(): FirestoreDocumentData;
}

interface FirestoreQuerySnapshot {
  docs: FirestoreQueryDocumentSnapshot[];
  size: number;
  empty: boolean;
  forEach(callback: (doc: FirestoreQueryDocumentSnapshot) => void): void;
}

interface FirestoreAggregateQuery {
  get(): Promise<{ data(): { count: number } }>;
}

interface FirestoreQuery {
  where(fieldPath: string, opStr: WhereFilterOp, value: unknown): FirestoreQuery;
  orderBy(fieldPath: string, directionStr?: OrderByDirection): FirestoreQuery;
  limit(limit: number): FirestoreQuery;
  limitToLast(limit: number): FirestoreQuery;
  offset(offset: number): FirestoreQuery;
  startAt(snapshot: FirestoreDocumentSnapshot): FirestoreQuery;
  startAt(...fieldValues: unknown[]): FirestoreQuery;
  startAfter(snapshot: FirestoreDocumentSnapshot): FirestoreQuery;
  startAfter(...fieldValues: unknown[]): FirestoreQuery;
  endAt(snapshot: FirestoreDocumentSnapshot): FirestoreQuery;
  endAt(...fieldValues: unknown[]): FirestoreQuery;
  endBefore(snapshot: FirestoreDocumentSnapshot): FirestoreQuery;
  endBefore(...fieldValues: unknown[]): FirestoreQuery;
  get(): Promise<FirestoreQuerySnapshot>;
  count(): FirestoreAggregateQuery;
  select(...fieldPaths: string[]): FirestoreQuery;
}

interface FirestoreCollectionReference extends FirestoreQuery {
  id: string;
  path: string;
  parent: FirestoreDocumentReference | null;
  doc(documentPath?: string): FirestoreDocumentReference;
  add(data: FirestoreDocumentData): Promise<FirestoreDocumentReference>;
  listDocuments(): Promise<FirestoreDocumentReference[]>;
}

interface FirestoreDocumentReference {
  id: string;
  path: string;
  parent: FirestoreCollectionReference;
  collection(collectionPath: string): FirestoreCollectionReference;
  get(): Promise<FirestoreDocumentSnapshot>;
  set(data: FirestoreDocumentData, options?: { merge?: boolean; mergeFields?: string[] }): Promise<unknown>;
  update(data: FirestoreDocumentData): Promise<unknown>;
  delete(): Promise<unknown>;
  listCollections(): Promise<FirestoreCollectionReference[]>;
}

interface FirestoreWriteBatch {
  set(ref: FirestoreDocumentReference, data: FirestoreDocumentData, options?: { merge?: boolean }): this;
  update(ref: FirestoreDocumentReference, data: FirestoreDocumentData): this;
  delete(ref: FirestoreDocumentReference): this;
  commit(): Promise<unknown[]>;
}

interface FirestoreTransaction {
  get(ref: FirestoreDocumentReference): Promise<FirestoreDocumentSnapshot>;
  set(ref: FirestoreDocumentReference, data: FirestoreDocumentData, options?: { merge?: boolean }): this;
  update(ref: FirestoreDocumentReference, data: FirestoreDocumentData): this;
  delete(ref: FirestoreDocumentReference): this;
}

interface Firestore {
  collection(collectionPath: string): FirestoreCollectionReference;
  doc(documentPath: string): FirestoreDocumentReference;
  collectionGroup(collectionId: string): FirestoreQuery;
  getAll(...refs: FirestoreDocumentReference[]): Promise<FirestoreDocumentSnapshot[]>;
  getAll(refs: FirestoreDocumentReference[], options?: { fieldMask?: string[] }): Promise<FirestoreDocumentSnapshot[]>;
  runTransaction<T>(updateFunction: (transaction: FirestoreTransaction) => Promise<T>): Promise<T>;
  batch(): FirestoreWriteBatch;
  listCollections(): Promise<FirestoreCollectionReference[]>;
}

// ─── Auth ─────────────────────────────────────────────────────────────────────

interface UserRecord {
  uid: string;
  email?: string;
  emailVerified: boolean;
  displayName?: string;
  photoURL?: string;
  phoneNumber?: string;
  disabled: boolean;
  metadata: { creationTime?: string; lastSignInTime?: string };
  customClaims?: Record<string, unknown>;
  tokensValidAfterTime?: string;
  tenantId?: string;
}

interface CreateUserRequest {
  uid?: string;
  email?: string;
  emailVerified?: boolean;
  displayName?: string;
  photoURL?: string;
  phoneNumber?: string;
  password?: string;
  disabled?: boolean;
}

interface UpdateUserRequest extends Omit<CreateUserRequest, "uid"> {
  customClaims?: Record<string, unknown> | null;
}

interface ListUsersResult {
  users: UserRecord[];
  pageToken?: string;
}

interface FirebaseAuth {
  getUser(uid: string): Promise<UserRecord>;
  getUserByEmail(email: string): Promise<UserRecord>;
  getUserByPhoneNumber(phoneNumber: string): Promise<UserRecord>;
  listUsers(maxResults?: number, pageToken?: string): Promise<ListUsersResult>;
  createUser(properties: CreateUserRequest): Promise<UserRecord>;
  updateUser(uid: string, properties: UpdateUserRequest): Promise<UserRecord>;
  deleteUser(uid: string): Promise<void>;
  deleteUsers(uids: string[]): Promise<{ successCount: number; failureCount: number }>;
  setCustomUserClaims(uid: string, customUserClaims: Record<string, unknown> | null): Promise<void>;
  verifyIdToken(idToken: string, checkRevoked?: boolean): Promise<{ uid: string; [key: string]: unknown }>;
  createCustomToken(uid: string, developerClaims?: Record<string, unknown>): Promise<string>;
  revokeRefreshTokens(uid: string): Promise<void>;
}

// ─── App ──────────────────────────────────────────────────────────────────────

interface FirebaseApp {
  name: string;
  options: Record<string, unknown>;
  firestore(): Firestore;
  auth(): FirebaseAuth;
}

// ─── Admin module ─────────────────────────────────────────────────────────────

interface AdminFieldValue {
  serverTimestamp(): FirestoreFieldValue;
  delete(): FirestoreFieldValue;
  increment(n: number): FirestoreFieldValue;
  arrayUnion(...elements: unknown[]): FirestoreFieldValue;
  arrayRemove(...elements: unknown[]): FirestoreFieldValue;
}

interface AdminTimestamp {
  now(): FirestoreTimestamp;
  fromDate(date: Date): FirestoreTimestamp;
  fromMillis(ms: number): FirestoreTimestamp;
}

interface AdminFirestoreModule {
  FieldValue: AdminFieldValue;
  Timestamp: AdminTimestamp;
  FieldPath: {
    documentId(): unknown;
  };
  GeoPoint: new (lat: number, lng: number) => FirestoreGeoPoint;
}

interface Admin {
  firestore: AdminFirestoreModule & ((app?: FirebaseApp) => Firestore);
  auth: (app?: FirebaseApp) => FirebaseAuth;
}

// ─── Globals ──────────────────────────────────────────────────────────────────

/** Firestore database instance for the active connection. */
declare const db: Firestore;

/** Firebase Auth instance for the active connection. */
declare const auth: FirebaseAuth;

/** Firebase App instance for the active connection. */
declare const app: FirebaseApp;

/** firebase-admin module — use admin.firestore.FieldValue, admin.firestore.Timestamp, etc. */
declare const admin: Admin;
`;

const JSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      checkJs: false,
      target: "ES2020",
      module: "commonjs",
    },
    include: ["./**/*.js", "./**/*.ts", "globals.d.ts"],
  },
  null,
  2
);

/**
 * Ensures the queries directory exists and writes IntelliSense support files
 * (jsconfig.json and globals.d.ts) if they are not already present.
 * Safe to call repeatedly — never overwrites existing files.
 */
export function ensureQueriesInfra(queriesDir: string): void {
  fs.mkdirSync(queriesDir, { recursive: true });

  const jsconfigPath = path.join(queriesDir, "jsconfig.json");
  if (!fs.existsSync(jsconfigPath)) {
    fs.writeFileSync(jsconfigPath, JSCONFIG, "utf-8");
  }

  const globalsPath = path.join(queriesDir, "globals.d.ts");
  if (!fs.existsSync(globalsPath)) {
    fs.writeFileSync(globalsPath, GLOBALS_DTS, "utf-8");
  }
}
